### ISSUE TITLE
[1.16.5] Use 1.17's Goat Horn animation for the Ravager Horn. Ravager Horns aren't edible ya' know.

### ISSUE THREAD

**Issue by MagmaSlime123** [izofar/takes-a-pillage#11]

**Comment by lxly9** [comment]
yup exactly

**Comment by lxly9** [comment]
(still used in 1.19.2)

**Comment by izofar** [comment]
Fixed for 1.19.2 in [3d173d3](https://github.com/izofar/takes-a-pillage/commit/3d173d3ea95a248db255a0e4b6132ae96f1d5309). Other versions pending

**Comment by izofar** [comment]
Fixed for 1.18.2 in [5eda949](https://github.com/izofar/takes-a-pillage/commit/5eda949c940a7970ddabcb61f947ee0c9301848a). 1.16.5 Pending

**Comment by izofar** [comment]
Fixed for 1.16.5 in [202c7b5](https://github.com/izofar/takes-a-pillage/commit/202c7b582357f7ca15256648c81ddfcaa89d02da)
