### ISSUE TITLE
Incompability with C2ME

### ISSUE THREAD

**Issue by AntonIXO** [izofar/takes-a-pillage#14]
Hello, 

Crash report: https://pastebin.com/bRBZKuy1
Userful tool for mapping crashs: 
https://shartte.github.io/minecraft-mapper/

**Comment by ZestyBlaze** [comment]
I can't lie, I'm afraid I don't know if that's a code fault of ours or C2ME, do you mind putting it on their issues tracker too so they can take a look and we'll figure it out?

**Comment by toinouH** [comment]
I sent a message to ishland about this issue. It might take a while before we get something from him as he is offline for a little moment.

**Comment by AntonIXO** [comment]
> I sent a message to ishland about this issue.

No news?

**Comment by ishland** [comment]
This crash is caused by the outdated Biome Makeover. This is fixed in their 1.6.1 release but you are still running 1.6.0.

**Comment by ZestyBlaze** [comment]
There we go, @AntonIXO if you update Biome Makeover you should be good
