### ISSUE TITLE
Clay Golem and Iron Golem natural spawning

### ISSUE THREAD

**Issue by Arbee4ever** [izofar/takes-a-pillage#17]
Could you add an Option to make 50% of them Clay Golems and the other 50% Iron Golem?

**Comment by izofar** [comment]
One of my intentions is to turn the toggle switch into a proportion, yes

**Comment by izofar** [comment]
Implemented for 1.19.2 with [e162e8d](https://github.com/izofar/takes-a-pillage/commit/e162e8d563468b69fb12e307cf1f68d6b552559e). Other versions pending
