### ISSUE TITLE
Golem summoning

### ISSUE THREAD

**Issue by DrPingas8** [izofar/takes-a-pillage#2]
For me when using the /summon command or the spawn egg from guard villagers to summon the iron golem it just spawns the clay golem. It also does it for other golem mobs from other mods. Not sure if its a compatibility issue with another mod.

**Comment by izofar** [comment]
Yes, this is an issue with my mod. Thank you for raising

**Comment by izofar** [comment]
Fixed. 1.19.2: [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31), 1.18.2: [7de592e](https://github.com/izofar/takes-a-pillage/commit/7de592ee776df4129d7cbca5d1fd4bbf2e67cc7a), 1.16.5: [83699e2](https://github.com/izofar/takes-a-pillage/commit/83699e20e73928f8856d55581cc5bc74dc4ae522)
