### ISSUE TITLE
1.20.1 doesn't seem to be functioning for me

### ISSUE THREAD

**Issue by MLPShockfury** [izofar/takes-a-pillage#33]
### Describe the Bug

Forge fully loads, and recognizes the mod being installed, however in game, nothing appears to actually be being added from ItTakesAPillage, no structures, Clay Golems, ect.

I made sure to create a separate instance as well to see if any of the other mods i use were overwriting it somehow, and none of them were, even when ItTakesAPillage is the only mod being loaded, none of its features are present in game.

### Reproduction Steps

Load the mod on version 1.20.1

### Expected Result

The mods features being present in game.

### Operating System

Windows 11

### Mod Version

1.2.1

### Minecraft Version

1.19.2

### Forge Version

Forge 47.2.0 for MC 1.20.1

### Other Mods

None

**Comment by Vemper1111** [comment]
How do you even want to load 1.19.2 mod on newer version? If there said that mod only on 1.19.2, it means that it won't work on other version, especially on 1.20.x versions

**Comment by MLPShockfury** [comment]
Im not trying to load a 1.19.2 mod on 1.20.1, i got the mod from Curseforge which lists it as 1.20.1, this may be a false version tracker issue.
The issue tracker on github had no options for 1.20.1 so that is why i specified the version using every other fill in box.

I have since moved on from needing or wanting to use this mod.
You should also look into being less snide with your choice of wording as the first thought that comes to mind reading it is 'unhelpful dickhead', and i have since blocked you at time of posting.
