### ISSUE TITLE
[1.19 - Suggestion] Config for disabling pillage siege at night

### ISSUE THREAD

**Issue by RedBeast1959** [izofar/takes-a-pillage#4]
Before starting, thank you for making this amazing mod. Me and my friends added this mod to custom modpack and really enjoying it.

But we dislike siege event because we can't prevent it no matter what light level or mobspawn preventing mod. So we added certain mod that prevent village zombie siege event and turn off every other mods config that generate simillar siege events.

So I was wondering if you could add some config to turn on/off pillager night siege event?

Thanks again.

**Comment by izofar** [comment]
Fixed: 1.19.2: [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31), 1.18.2: [7de592e](https://github.com/izofar/takes-a-pillage/commit/7de592ee776df4129d7cbca5d1fd4bbf2e67cc7a), 1.16.5: [7afe6fb](https://github.com/izofar/takes-a-pillage/commit/7afe6fbbdfd04cb2bbb6903ec0b14874b69e056e)
