### ISSUE TITLE
Clay Golems

### ISSUE THREAD

**Issue by swuggah** [izofar/takes-a-pillage#5]
I have a village with around 40 or 50 villagers at most. There is constantly atleast 50 clay golems roaming around the paths, on top of houses, etcetera. 50 is probably a lowball. Every turn, every path, is just flooded with clay golems.

**Comment by TheSultryBadger** [comment]
Same problem here, sort of. I have a hole with 8 Villagers and about 320,000 Clay golems (maybe a slight exaggeration).  Where before the update I had one iron Golem. Is there a command I can use to kill them all so I can actually access my villagers?

**Comment by swuggah** [comment]
If you play singleplayer, you can go in your takesapillage mod file and
mark replace iron golems with clay golems as false instead of true. I play
on a server though and don't know how to tell the server not to replace the
iron golems.

**Comment by izofar** [comment]
Fixed: 1.19.2: [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31), 1.18.2: [7de592e](https://github.com/izofar/takes-a-pillage/commit/7de592ee776df4129d7cbca5d1fd4bbf2e67cc7a), 1.16.5: [7afe6fb](https://github.com/izofar/takes-a-pillage/commit/7afe6fbbdfd04cb2bbb6903ec0b14874b69e056e)
