### ISSUE TITLE
[1.16.5] Suggestion: implement a config to control generation rate of structures 

### ISSUE THREAD

**Issue by antibang** [izofar/takes-a-pillage#7]
If this is not exactly easy or not planned at all, I get it, but structures seem to spawn *very* often, especially in plains-like biomes. You can see in the screenshot I attached that the structures are VERY close together. I wanted to possibly make these one of the harder structures in my modpack, but since they are so common, it is a bit frustrating to work with the amount that they spawn and try to redo the loot tables to balance everything. Plus, I wanted to finally include a rare item or two, but again, just hard to do that when the structures are very, very common.

Otherwise, this mod is absolutely amazing! I really want to include it and have it a part of my modpack, but as you can see some of them are quite literally next to each other, or just generally super close to one another. The Better Villages mod/datapack doesn't help the fact that it looks like structures in general overspawn, but hopefully you understand :)

Not even sure if this is not intended and if other people are experiencing it.

![2022-10-10_05 54 08](https://user-images.githubusercontent.com/79492924/194852536-7e715386-a80b-43de-abe3-2ba52d0a8391.png)

**Comment by izofar** [comment]
My goodness that's common. Way more than I intended. I'll address that in the next update

**Comment by izofar** [comment]
Fixed: 1.19.2: [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31), 1.18.2: [7de592e](https://github.com/izofar/takes-a-pillage/commit/7de592ee776df4129d7cbca5d1fd4bbf2e67cc7a), 1.16.5: [7afe6fb](https://github.com/izofar/takes-a-pillage/commit/7afe6fbbdfd04cb2bbb6903ec0b14874b69e056e)
