### ISSUE TITLE
[1.19.2] @Reliquary - Twilight Cloak crashes the server randomly when near Archer from @Takes a Pillage.

### ISSUE THREAD

**Issue by Gbergz** [izofar/takes-a-pillage#9]
Title^
Now this could very well not be an issue in your mod but I'm gonna report it here anyways to be sure. 
I've reported it on reliquarys page already aswell.

Wearing the Twilight Cloak from @Reliquary whilst anywhere close to an @Takes A Pillage - Archer seems to crash the server. Not entirely sure why.

**Crash-Report:** https://gist.githubusercontent.com/Gbergz/fee336d7f7bf16f0d94f14d1419e8421/raw/784e6a60dcf7f5cb60d2e0f5d4afa0fbc6627540/gistfile1.txt

**Minecraft:** 1.19.2
**Forge:** 43.1.47
**Takes a Pillage**: 1.0.2-1.19.2
**Reliquary Version:** 1.19.2-2.0.20.1166

**-** Gbergz

**Comment by izofar** [comment]
Fixed in [c7b81ae](https://github.com/izofar/takes-a-pillage/commit/c7b81ae3c9b1425a9627daa853b70f0af9cbdd31)

Thanks for the report!
